title: Lasse's Webpage
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation links (optional)
navigation:
  - title: Home
    url: /

# Other configuration options
markdown: kramdown
highlighter: rouge